name: React App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js 20 (same as local)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # 3. Verify Node.js version
      - name: Check Node.js version
        run: node -v

      # 4. Remove old modules & lock file
      - name: Clean install
        run: |
          rm -rf node_modules package-lock.json
          npm install

      # 5. Build React app
      - name: Build React app
        run: npm run build

      # 6. Deploy via FTP
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.arakash.com
          port: 21
          protocol: ftp
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist
          server-dir: /public_html/
          dangerous-clean-slate: true
